Inital pass at adding home assistant in.
MichaIng/DietPi pull request #1087
Opened 2017-07-19 03:22 UTC by sytone

Started validation, do not have a card to test moving the data directory so not sure on the best solution there. Please comment on the initial approach. I have hard coded the account and usage of a virtual env as I do not see an example pf prompting the user. The defaults are good however and follow the home assistant approach. 

This is related to #935

2017-07-19 12:58 UTC, Fourdee commented on dietpi/dietpi-software
> +			#ln -sf "$FP_DIETPI_USERDATA_DIRECTORY"/homeassistant /home/homeassistant/.homeassistant
You may need to also set permissions to the DietPi user data directory, for ```homeassistant``` user.

All permissions are applied here, at the end of installation:
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software#L7319-L7353

eg:
```
chown -R homeassistant:homeassistant "$FP_DIETPI_USERDATA_DIRECTORY"/homeassistant
```

2017-07-19 13:01 UTC, Fourdee commented
@sytone 

Great work, really impressive 👍 

Love the addition of comment notes regarding steps required.

Also need uninstall code for this software title.

2017-07-19 13:08 UTC, Fourdee commented on dietpi/dietpi-software
> +			#mkdir -p "$FP_DIETPI_USERDATA_DIRECTORY"/homeassistant
```#mkdir -p "$FP_DIETPI_USERDATA_DIRECTORY"/homeassistant``` not required. The symlink command below will generate this folder.

2017-07-19 13:12 UTC, Fourdee commented
@sytone 

> do not have a card to test moving the data directory so not sure on the best solution there.

Don't need one. The User data directory exists by default, even on SD card only installs.

If the ```/home/homeassistant/.homeassistant``` directory does not contain any data can just remove the folder and replace with symlink:
```
root@DietPi:~# FP_DIETPI_USERDATA_DIRECTORY='/mnt/dietpi_userdata'^C            root@DietPi:~# rm -R /home/homeassistant/.homeassistant

root@DietPi:~# ln -sf "$FP_DIETPI_USERDATA_DIRECTORY"/homeassistant /home/homeassistant/.homeassistant

root@DietPi:~# ls -lha /home/homeassistant/
total 8.0K
drwxr-xr-x 2 root root 4.0K Jul 19 13:11 .
drwxr-xr-x 4 root root 4.0K Jul 19 13:07 ..
lrwxrwxrwx 1 root root   34 Jul 19 13:11 .homeassistant -> /mnt/dietpi_userdata/homeassistant

```

2017-07-28 21:41 UTC, sytone commented on dietpi/dietpi-software
> +			#ln -sf "$FP_DIETPI_USERDATA_DIRECTORY"/homeassistant /home/homeassistant/.homeassistant
must have missed that as I thought I already added it. Whoops! I have updated the apply section now.

2017-07-28 22:04 UTC, sytone commented
The folder will not have anything until the service starts and then it generates its own configuration if there is none there.

2017-08-02 18:57 UTC, sytone commented
ok, I have resolved out some issues with the install process and fixed the access to the configuration. Need tpo look at update process in the future.

2017-08-04 07:35 UTC, myself-69 approved these changes

2017-08-04 10:23 UTC, Fourdee requested changes
@sytone 

Great work, thanks for making those changes 👍 

We are missing one change, regarding the ```AGP``` removal of shared libs. Please remove this line from the code, then I can merge.

2017-08-04 10:23 UTC, Fourdee commented on dietpi/dietpi-software
> +			AGP python3 python3-pip libssl-dev cmake libc-ares-dev uuid-dev daemon curl libgnutls28-dev libgnutlsxx28 nmap net-tools sudo libglib2.0-dev cython3 libudev-dev python3-sphinx python3-setuptools l
During uninstalls, do not remove shared libraries (eg: python, cmake,  etc) and this could break other software installations. Removing ```-dev``` packages should also be avoided as this may remove something the user needed for their "manual" software installs/projects.

I generally only remove packages/software, if it would "never" effect other software, or the users "general use". Ideally, target the software title, minus possible shared items.

I believe the whole ```AGP``` line could be removed here to be safe.

2017-08-04 10:23 UTC, Fourdee commented on dietpi/dietpi-software
We need to increase the following item to ```158```, to ensure your new array exists.
```
TOTAL_SOFTWARE_INDEXS_HARDLIMIT=157
```

2017-08-04 10:23 UTC, Fourdee commented on dietpi/dietpi-software
> +			su -s /bin/bash homeassistant <<EOF
Nice 👍

2017-08-08 15:51 UTC, sytone commented on dietpi/dietpi-software
> +			AGP python3 python3-pip libssl-dev cmake libc-ares-dev uuid-dev daemon curl libgnutls28-dev libgnutlsxx28 nmap net-tools sudo libglib2.0-dev cython3 libudev-dev python3-sphinx python3-setuptools l
ok, thanks for the comment. Ill remove this in the next iteration. Most of the actual install happens in python.

2017-08-08 15:56 UTC, sytone commented on dietpi/dietpi-software
I just looked and it is 158. Am I missing something?

2017-08-09 09:16 UTC, Fourdee approved these changes

2017-08-09 09:16 UTC, Fourdee commented
@sytone 

Thanks for the changes, great work 👍

2017-08-09 09:16 UTC, merged

2017-09-06 07:23 UTC, elRadix commented
@Fourdee  how can I exclude home-assistant from dietpi-service stop/start every time I perform install/update/backup actions? I don't want my home automation to be unavailable during these times.

2017-09-06 11:55 UTC, Fourdee commented
@elRadix 

Currently, you'd need to modify the source code on your install:
```
/DietPi/dietpi/dietpi-services
```

Remove the line:
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-services#L103

2017-09-06 15:47 UTC, elRadix commented
@Fourdee thank you

An exclude file would be great indeed same as the include that's already existing.

2017-09-07 01:45 UTC, sytone commented
IS there a way to add to the existing menus software specific configuration menus? Could a Software Configuration menu be added then apps can register scripts that can configure them? That way HA could have one to enable/disable service restart with the rest of dietpi services. 

Software Optimized   Select DietPi optimized software for installation
Software Additional  Select additional Linux software for installation 
Software Configuration Configure installed software <- This would be the new entry. 

Thoughts?

2017-09-09 15:28 UTC, Fourdee commented
@sytone 

> Software Configuration Configure installed software <- This would be the new entry.

Love this idea. We could have sections for each peice of installed software, eg:
- List config file locations, selecting them opens it up in nano to edit

> That way HA could have one to enable/disable service restart with the rest of dietpi services.

dietpi-services would need to be modified to read from a "exclude file" to skip those services. We could then generate the exclude file as needed.

2017-09-17 16:02 UTC, sytone commented
ok, I have been looking at this and how not to duplicate information around the system to make configuration easier. At the moment the configuration is scattered across files. It would be good to try and bring it together. 

- Move to something like python to handle the configuration and scripts in a more controlled way. 
  - PRO: We have all or pythons pre-existing commands available by default. 
  - PRO: Huge amount of modules available to enrich the system
  - CON: Overhead of needing python on all boards 
  - CON: Size considerations. 

- Use jq in bash to move configuration to a json file and out of scripts
  - PRO: All configuration goes to a single json file. 
  - CON: rewrite all scripts to use jq 
  - CON: jq needed on all boards
  - CON: Still in bash and manipulation is not straight forward.

2017-09-18 14:03 UTC, Fourdee commented
@sytone 

I personally dislike Python, the code layout and syntax simply looks "wrong" to me. Its also inefficient. If we were to move DietPi to another language, I'd personally go with C++ and use a SQL plugin.
It would take months of uninterrupted work to complete this, and thats not going to happen any time soon unfortunately.

Another option, which we use already, is to store everything in a file, then read it like a database, eg:
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-process_tool#L367-L392

Above is awk $X based, however, it could be done on lines, and or, sections using a word start and end trigger based on install index, eg:
```
_START_128
/etc/mpd.conf #mpd conf
/etc/mpd_somethingelse.conf #mpd extra info
_END_128

```

2017-09-23 17:20 UTC, sytone commented
@Fourdee are you opposed to using something like jq to format the data in json blocks so we are not at the mercy of a type or newline issue for schema problems? This still allows us to clean out the scripts so all the software metadata is in a single place and settings or values can be stored in a local json file alongside the catalogue of software in place. 

Something like this
```
test.json file contents
{
    "version":"v155",
    "software": [
        {
            "id": 23,
            "name":"LXDE",
            "description":"ultra lightweight desktop",
            "software_category":0,
            "software_type":0,
            "requires":["alsa","xserverxorg"],
            "forum_link":"f=8&t=5#p42",
            "hardware_arch":"",
            "hardware_model":""
        },
        {
            "id": 24,
            "name":"MATE",
            "description":"desktop enviroment",
            "software_category":0,
            "software_type":0,
            "requires":["alsa","xserverxorg"],
            "forum_link":"f=8&t=5&start=60#p2073",
        }        
    ]
}

root@homeassistant:~# cat test.json | jq '.software[] | select(.id == 24)'
{
  "id": 24,
  "name": "MATE",
  "description": "desktop enviroment",
  "software_category": 0,
  "software_type": 0,
  "requires": [
    "alsa",
    "xserverxorg"
  ],
  "forum_link": "f=8&t=5&start=60#p2073"
}
root@homeassistant:~# cat test.json | jq '.software[] | select(.name == "MATE")'
{
  "id": 24,
  "name": "MATE",
  "description": "desktop enviroment",
  "software_category": 0,
  "software_type": 0,
  "requires": [
    "alsa",
    "xserverxorg"
  ],
  "forum_link": "f=8&t=5&start=60#p2073"
}

root@homeassistant:~# cat test.json | jq '.software[].id' | while read object; do
>   echo "$object"
> done
23
24

--




```

2017-09-23 20:05 UTC, Fourdee commented
@sytone 

>  are you opposed to using something like jq to format the data in json blocks so we are not at the mercy of a type or newline issue for schema problems? 

Not at all, if it cleans up the code and makes the workflow easier for everyone, i'am all for it. 
Ideally, if we could have a working prototype example of how this would work, we can see if it benefits the project contributors and our users?

> Also completely random through, to reduce footprint and still allow separation of the install/uninstall/update/configure scripts for software zip them all up and have the system extract the ones needed for the installed software. Just thinking about maintenance and structure to make it easier for others to contribute.

I really like the idea of having the install/uninstall sections contained within unique script files, but each script file will need to support the global vars we use in ```dietpi-software``` (eg: $HW_MODEL / $HW_ARCH / $FP_DIETPIUSERDATA etc). 
Could try and take this further by globally setting vars at system level, eg: ```export VAR=value``` etc, then we wouldn't have to file load these in every script. But, they would need to be updated/refreshed at times.

Regardless, we shouldn't focus on "over-complicating", instead, "simplifying", as long as it benefits project workflow for contributors and our end users.
But I completely agree that ```dietpi-software``` should be cleaned up to remove the install/uninstall (and array) code, instead having it located externally and imported on demand.

2017-10-13 20:19 UTC, elRadix commented
Is there a way to upgrade the next version of python without breaking the system?

`[homeassistant.bootstrap] Python 3.4 support has been deprecated and will be removed in the begining of 2018. Please upgrade Python or your operating system. More info: https://home-assistant.io/blog/2017/10/06/deprecating-python-3.4-support/`

2017-10-14 14:06 UTC, Fourdee commented
@elRadix 

Easiest solution is to upgrade to Stretch:
```
python3 is already the newest version (3.5.3-1)
```

https://github.com/Fourdee/DietPi/issues/475#issue-171250292

2017-10-14 16:14 UTC, elRadix commented
@Fourdee, I already have a lot of apps running, upgrading is only possible if I install a new image and start from scratch? 

Is there an easy way to upgrade to Stretch or upgrading python?
I also think using diepti-backup to restore my config might not work on Strecht

2017-10-26 02:13 UTC, sytone commented
I have a pull that has the pyenv in it. It allows better control of the python versions and allow multiple versions to be installed and not impact the distribution version.

2017-10-26 18:30 UTC, Fourdee commented
@sytone 

> I have a pull that has the pyenv in it. It allows better control of the python versions and allow multiple versions to be installed and not impact the distribution version.

Thanks. I've merged this for testing: https://github.com/Fourdee/DietPi/issues/1145#issuecomment-339755566