DietPi-LetsEncrypt | Error handling + further rework
MichaIng/DietPi pull request #1738
Opened 2018-04-29 16:19 UTC by MichaIng

Via Forum: https://dietpi.com/phpbb/viewtopic.php?f=11&t=1909
+ DietPi-LetsEncrypt | Skip any webserver config edit, if CertBot execution returns error: https://dietpi.com/phpbb/viewtopic.php?f=11&t=1909
+ DietPi-LetsEncrypt | Lighttpd SSL config upgrade according to Mozilla SSL generator: https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=lighttpd-1.4.35&openssl=1.0.1t&hsts=yes&profile=intermediate
+ DietPi-LetsEncrypt | Minor code and error handling improvements, revert path variable naming scheme
   - `ps aux | grep` vs `pgrep`: https://github.com/Fourdee/DietPi/issues/1510#issuecomment-385370492
- [x] Added changelog entries
________________
<s>**WIP: testing required**</s>
**Testing and fixing done, ready to merge!**
- [x] Stretch + Apache until certbot cmd
- [x] Stretch + Nginx until certbot cmd
- [x] Stretch + Lighttpd until certbot cmd
- [x] Stretch + Minio until certbot cmd
- [x] Stretch + Apache until end (add self-signed certs for webserver links/tasks)
- [x] Stretch + Nginx until end (add self-signed certs for webserver links/tasks)
- [x] Stretch + Lighttpd until combined.pem error handler
- [x] Stretch + Lighttpd until end (add self-signed certs for webserver links/tasks)
  - 🈯️ Error with `(` inside pattern. Treated specially with ext. regex, expecting `)`, `\(` just works for `grep`, but `sed` somehow needs additional escaping, which then fails `grep` check. Confusing as with direct call `grep` and `sed` need/understand the exact same level of escaping. Sub sub script/function seems to mix things up... Perhaps we need to remove ext. regex again from `G_CONFIG_INJECT`. **€: Recheck success!**
  - 🈯️ `G_CONFIG_INJECT` pattern as well: `\\t` double escaping or better direct tab symbol needed. **€: Recheck success!**
  - 🈯️ `´´` special symbols inside `cat` leads to execution of `openssl` command. **€: Recheck success!**
  - 🈯️ Edit `sed` commands to just apply on first match! **€: Recheck success!**
  - 🈯️ `sed -Ei` is needed, `sed -iE` will create new file with `E` added to file name. **€: Recheck success!**
- [x] Stretch + Minio until end (add self-signed certs for webserver links/tasks)
- [x] Jessie + Apache until end (add self-signed certs for webserver links/tasks)
  - 🈯️ pgrep `-i` option doesn't exist on Jessie **€: Recheck success!**
- [x] Jessie + Nginx until end (add self-signed certs for webserver links/tasks)
  - 🈯️ G_CONFIG_INJECT fix sed adds instead of replaces accidentally **€: Recheck success!**
- [x] Jessie + Lighttpd until end (add self-signed certs for webserver links/tasks)
  - 🈯️ Just add `2>> logfile` after cat, to just log errors while allowing to forward file contents to combined.pem **€: Recheck success!**
- [x] Jessie + Minio until end (add self-signed certs for webserver links/tasks)
________________
- <s> [ ] Add CertBot from backports to re-enable TLS-SNI authentication method on Stretch?</s> **Adding to separate PR**

2018-04-30 14:33 UTC, Fourdee requested changes
G_RUN_CMD changed required, aside from that, looks good 👍

2018-04-30 14:33 UTC, Fourdee commented on dietpi/dietpi-letsencrypt
> +			G_RUN_CMD cat $fp_cert_dir/privkey.pem $fp_cert_dir/cert.pem > $fp_cert_dir/combined.pem
Redirects and pipes are not supported with ```G_RUN_CMD``` ☹️ 
```
root@DietPi:~# G_RUN_CMD cat /etc/network/interfaces > test
root@DietPi:~# cat test
[  OK  ] Root access verified.
[  OK  ] cat /etc/network/interfaces
```

2018-04-30 14:33 UTC, Fourdee commented on dietpi/dietpi-letsencrypt
> +		elif pgrep -i '[n]ginx' &> /dev/null; then
Interesting, seems ```pgrep``` automatically removes the process which checks for it, so its not added to the count:
Starting with ```[n]``` is not then needed, but no harm 😃 
```
root@DietPi:~# pgrep -i bash
2318
2402
root@DietPi:~# pgrep -i [b]ash
2318
2402
root@DietPi:~# ps aux | grep bash
root      1002  0.0  0.0   4308   580 pts/0    S+   15:19   0:00 grep --color=auto bash
root      2318  0.0  0.1   6132  4036 ?        Ss   13:36   0:00 -bash
root      2402  0.0  0.1   7144  5320 pts/0    Ss   13:37   0:00 -bash
root@DietPi:~# ps aux | grep [b]ash
root      2318  0.0  0.1   6132  4036 ?        Ss   13:36   0:00 -bash
root      2402  0.0  0.1   7144  5320 pts/0    Ss   13:37   0:00 -bash
```

2018-04-30 14:34 UTC, Fourdee commented
@MichaIng 

> WIP: testing required

Not the easiest thing to test Certbot, hehe 👍

2018-05-01 10:22 UTC, MichaIng commented on dietpi/dietpi-letsencrypt
> +			G_RUN_CMD cat $fp_cert_dir/privkey.pem $fp_cert_dir/cert.pem > $fp_cert_dir/combined.pem
Indeed, thanks for hint, will make commit later, also to add raw IP test.
€: Done, added alternative error handling, as this is critical.

2018-05-01 10:23 UTC, MichaIng commented on dietpi/dietpi-letsencrypt
> +		elif pgrep -i '[n]ginx' &> /dev/null; then
😆 Jep thought the same, just took `-i` and `[n]` from the old code.
€: Removed [ ]

2018-05-01 10:26 UTC, MichaIng commented
@Fourdee 
Jep always a problem. I will add some fix + raw IP as domain check and do test with all webservers until certbot execution, then locally allow errors and redo to test webserver adjustments.

2018-05-03 00:43 UTC, MichaIng commented
@Fourdee 
- Testing done. Verified functionality of config adjustments via self-signed certificates and manually ignoring/skipping certbot binary execution of all web browsers on Jessie and Stretch. Also cron job and renewal systemd additions tested.
- I will merge, as there is some urgent G_CONFIG_INJECT fix included that can mess up the testing systems.

2018-05-03 00:51 UTC, merged