v8.3
MichaIng/DietPi pull request #5363
Opened 2022-03-17 17:11 UTC by MichaIng

- DietPi-Drive_Manager | Adding an NFS drive now allows to select a specific export from an NFS server, detected via "showmount -e <IP/hostname>". Entering a custom path is still possible, including the single slash "/" which was always used before. If the NFS server has no root export defined via "fsid=0", this solves the issue that the full root directory structure is mounted and allows to mount multiple shares from the same server. Many thanks to @bamyasi for doing this suggestion: https://dietpi.com/phpbb/viewtopic.php?t=5488
- DietPi-Drive_Manager | NFS and Samba network drives can now be mounted to any directory on the server, not necessarily below /mnt.

2022-03-17 17:15 UTC, MichaIng commented
One issue is that `showmount` hangs very long (probably 90 seconds) if the IP/hostname is invalid or NFS server not reachable. It even cannot be aborted with CTRL+C, feels exactly like the systemd automount hang. `showmount` of course is not a mount attempt and has not something to do with systemd automount, but probably the underlying mechanism and timeout is the same. We print a notification when scanning is done, but it would be actually great if we could reduce the timeout, and then add some counter or so as better feedback for users.

2022-03-20 23:36 UTC, Joulinar requested changes
Something seems not to be working well. I setup a NFS server with 2 shares. The 2nd system running as NFS client is detection both shares. So far no issue. But I can't pass the step to specify mount point/directory on client side. The dialog did not continue.

2022-03-20 23:41 UTC, MichaIng commented
I missed the breaks to exit the loop when input was valid 🙈. Just fixed.

2022-03-20 23:50 UTC, MichaIng commented
Another issue, need to remove the allowed clients from `showmount` output.

2022-03-20 23:51 UTC, Joulinar commented
Mounting the share is not working. Looks like incorrect folder is mounted.

```
 ┌────────────────────────────────────────┤ DietPi-Drive_Manager | File viewer ├────────────────────────
 │                                                                                                      
 │ [FAILED] NFS mount failed with the following error output:                                           
 │                                                                                                      
 │ mount.nfs: mount(2): No such file or directory                                                       
 │ mount.nfs: trying 192.168.0.13 prog 100003 vers 3 prot TCP port 2049                                 
 │ mount.nfs: trying 192.168.0.13 prog 100005 vers 3 prot UDP port 44000                                
 │ mount.nfs: mount(2): Permission denied                                                               
 │ mount.nfs: access denied by server while mounting 192.168.0.13:/mnt/dietpi_userdata *                
 │ mount.nfs: timeout set for Mon Mar 21 00:48:09 2022                                                  
 │ mount.nfs: trying text-based options 'port=2049,vers=4.2,addr=192.168.0.13,clientaddr=192.168.0.12'  
 │ mount.nfs: trying text-based options 'port=2049,addr=192.168.0.13'                                   
 │ mount.nfs: prog 100003, trying vers=3, prot=6                                                        
 │ mount.nfs: prog 100005, trying vers=3, prot=17                                                       
 │                                                                                                      
 │                                                        <Ok>                                          
 │                                                                                                      
 └──────────────────────────────────────────────────────────────────────────────────────────────────────
```

doing it manually is working well

```
root@DietPi3:~# mkdir -p /mnt/nfs1
root@DietPi3:~# mount -t nfs 192.168.0.13:/mnt/dietpi_userdata /mnt/nfs1
root@DietPi3:~# df -h
Filesystem                         Size  Used Avail Use% Mounted on
/dev/root                           15G  2.9G   11G  22% /
devtmpfs                           454M     0  454M   0% /dev
tmpfs                              487M     0  487M   0% /dev/shm
tmpfs                              195M  2.9M  192M   2% /run
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              1.0G     0  1.0G   0% /tmp
tmpfs                               50M   36K   50M   1% /var/log
/dev/sda1                          127M   50M   77M  40% /boot
192.168.0.13:/mnt/dietpi_userdata   10G  846M  8.8G   9% /mnt/nfs1
root@DietPi3:~# ls -la /mnt/nfs1/
total 24
drwxrwxr-x 6 dietpi dietpi 4096 Sep 12  2021 .
drwxr-xr-x 7 root   root   4096 Mar 21 00:49 ..
drwxrwxr-x 2 dietpi dietpi 4096 Sep 12  2021 Music
drwxrwxr-x 2 dietpi dietpi 4096 Sep 12  2021 Pictures
drwxrwxr-x 2 dietpi dietpi 4096 Sep 12  2021 Video
drwxrwxr-x 2 dietpi dietpi 4096 Sep 12  2021 downloads
root@DietPi3:~#
```

2022-03-20 23:52 UTC, MichaIng commented
Hmm, multiple clients can be specified, separated by spaces. Means it will be difficult to reliably allow spaces in the export path. However, should be rare, and if needed can be entered manually.

2022-03-21 00:01 UTC, MichaIng commented
Okay, should work fine now. Resolved another minor issue that the default mount points are tried to be removed, even if they are currently used by another NFS/Samba mount.

I also verified that with a root defined via `fsid=0`, the absolute paths work as well as using `/` and other exports relative to this root, e.g. `/Video` when adding `/mnt/dietpi_userdata/Video` this to exports on the server with `/mnt/dietpi_userdata` being the root via `fsid=0`. So all forward/backwards compatible 🙂.

2022-03-21 00:11 UTC, Joulinar commented
looking good now. I was able to mount both NFS exports.

```
root@DietPi3:/mnt# df -h
Filesystem                         Size  Used Avail Use% Mounted on
/dev/root                           15G  2.9G   11G  22% /
devtmpfs                           454M     0  454M   0% /dev
tmpfs                              487M     0  487M   0% /dev/shm
tmpfs                              195M  2.9M  192M   2% /run
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              1.0G     0  1.0G   0% /tmp
tmpfs                               50M   36K   50M   1% /var/log
/dev/sda1                          127M   50M   77M  40% /boot
192.168.0.13:/mnt/nfs_export        10G  846M  8.8G   9% /mnt/nfs1
192.168.0.13:/mnt/dietpi_userdata   10G  846M  8.8G   9% /mnt/nfs2
root@DietPi3:/mnt#
```

Question: discovering the available mounts will always show all available NFS shares, even if already used/mounted. Not sure how much efforts it is, but would it be possible to hide shares already used/mounted?

2022-03-21 00:14 UTC, MichaIng commented
Good point. Should be trivial to exclude them by checking for the presents of the same host|IP:/path in fstab. But it is btw possible to mount the very same export two times.

2022-03-21 00:40 UTC, MichaIng commented
Okay not so trivial was the question about how to show the menu when all the shares are mounted already, especially if the user is not aware of it. I decided to instead show those shared but with the info that and where they are mounted already.

2022-03-21 00:45 UTC, Joulinar commented
I guess you tried to indicate where it has been mounted already?

```
/mnt/nfs_export      : Already mounted at:                 
/mnt/dietpi_userdata                                       
Custom               : Enter custom NFS server share path  
```

2022-03-21 01:02 UTC, MichaIng commented
Nasty syntax difficulties in awk when using double quotes. Went with a different approach for adding this info to the menu.

2022-03-21 01:12 UTC, Joulinar submitted a review, later dismissed
looks good now

2022-03-21 01:13 UTC, MichaIng commented
Also added the hint now that it may take up to 90 seconds before it times out. But indeed, testing all local IPs, existing or now, it fails immediately. Seems to be a very rare issue.

2022-03-21 01:17 UTC, merged